# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fccdb00e38dc6555eae406107d16af9f354779488b4faa4c55c47faf95218b2ed4cc7b8e6d542053807e2d6f9422e6f963a6f447ac4fa8e82f107ce47a68cd8

test:
  secret_key_base: 122a257bef1bebdb9b61f145949e12446bb859dd7e279720df6fcf94929ba574331bdb4a1818fe50555bde2f8bf56d49f41ffd08687ddf8b2ecd0a469e41eba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
